"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CalendarDays, Coins, IndianRupee, RefreshCw, TrendingDown, TrendingUp, Users } from "lucide-react";
type Row = Record<string, any>;
const presets = [["today","Today"],["7d","7 days"],["30d","30 days"],["this_month","This month"],["3m","3 months"],["6m","6 months"],["this_year","This year"],["custom","Custom"]];
const fmt=(v:unknown,d=0)=>Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:d});
const money=(v:unknown)=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const pct=(v:unknown)=>`${Number(v||0).toFixed(1)}%`;
function Card({label,value,sub,tone="#f97316",icon:Icon=Coins}:{label:string;value:string;sub?:string;tone?:string;icon?:any}){return <div className="ra-card"><span className="ra-icon" style={{color:tone,background:`${tone}12`}}><Icon size={18}/></span><strong>{value}</strong><span>{label}</span>{sub&&<small>{sub}</small>}</div>}
function Section({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="ra-section"><header><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</header>{children}</section>}
function Table({columns,rows}:{columns:[string,(r:Row)=>React.ReactNode][];rows:Row[]}){return <div className="ra-table-wrap"><table><thead><tr>{columns.map(([x])=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={String(r.id||r.category||r.name||r.code||i)}>{columns.map(([x,render])=><td key={x}>{render(r)}</td>)}</tr>):<tr><td colSpan={columns.length} className="ra-empty">No data in this period.</td></tr>}</tbody></table></div>}
function Stats({items}:{items:[string,string][]}){return <div className="ra-stat-list">{items.map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div>}
export default function RewardsAnalyticsClient(){
 const [preset,setPreset]=useState("30d"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const qs=new URLSearchParams({preset});if(preset==="custom"){qs.set("start",start);qs.set("end",end)}try{const res=await fetch(`/api/admin/rewards/analytics?${qs}`);const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to load analytics.");setData(body)}catch(e){setError(e instanceof Error?e.message:"Unable to load analytics.")}finally{setLoading(false)}},[preset,start,end]);
 useEffect(()=>{if(preset!=="custom"||(start&&end)){const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)}},[load,preset,start,end]);
 const max=Math.max(1,...(data?.trends||[]).map((r:Row)=>Math.max(r.issued,r.redeemed,r.expired)));
 return <main className="page-main ra-page"><div className="ra-toolbar"><div><h1>Rewards health & liability</h1><p>Read-only reporting from the canonical Damru ledger and customer balances.</p></div><div className="ra-filters"><CalendarDays size={16}/><select value={preset} onChange={e=>setPreset(e.target.value)}>{presets.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>{preset==="custom"&&<><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></>}<button onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"ra-spin":""}/>Refresh</button></div></div>
 {error&&<div className="ra-error"><AlertTriangle size={18}/>{error}</div>}{loading&&!data?<div className="ra-loading">Loading rewards analytics…</div>:data&&<>
 <div className="ra-kpis"><Card label="Gross issued" value={fmt(data.kpis.grossIssued)} sub={`${pct(data.kpis.comparison.issued)} vs prior`} icon={TrendingUp}/><Card label="Reward reversed" value={fmt(data.kpis.reversed)} sub={`Net ${fmt(data.kpis.netIssued)}`} tone="#dc2626" icon={TrendingDown}/><Card label="Redeemed" value={fmt(data.kpis.redeemed)} sub={`${pct(data.kpis.redemptionRate)} rate`} tone="#2563eb" icon={TrendingDown}/><Card label="Outstanding" value={fmt(data.kpis.outstanding)} sub={`${fmt(data.kpis.usersWithBalance)} holders`} tone="#7c3aed"/><Card label="Current liability" value={money(data.kpis.liability)} sub={`₹${data.conversionRate}/Damru`} tone="#dc2626" icon={IndianRupee}/><Card label="Active users" value={fmt(data.kpis.activeRewardUsers)} sub={`${fmt(data.engagement.noRewardActivity)} inactive`} tone="#059669" icon={Users}/></div>
 <div className="ra-grid ra-grid-2"><Section title="Issuance and redemption trends" subtitle={`Grouped by ${data.meta.groupBy} · Asia/Kolkata`}><div className="ra-chart">{data.trends.map((r:Row)=><div className="ra-bar-group" key={r.bucket}><div className="ra-bars"><i style={{height:`${r.issued/max*100}%`}}/><i style={{height:`${r.redeemed/max*100}%`}}/><i style={{height:`${r.expired/max*100}%`}}/></div><small>{r.bucket}</small></div>)}</div><div className="ra-legend"><span>Issued</span><span>Redeemed</span><span>Expired</span></div></Section><Section title="Liability & expiry" subtitle="Forecast covers lot-tracked credits"><div className="ra-mini-grid"><Card label="Reward debt" value={fmt(data.kpis.rewardDebt)} tone="#dc2626"/><Card label="Expired" value={fmt(data.kpis.expired)} tone="#dc2626"/><Card label="Restored" value={fmt(data.kpis.restored)} tone="#059669"/><Card label="Next 7 days" value={fmt(data.expiry.next7)}/><Card label="Next 30 days" value={fmt(data.expiry.next30)}/><Card label="Next 90 days" value={fmt(data.expiry.next90)}/><Card label="After 90 days" value={fmt(data.expiry.after90)}/></div></Section></div>
 <Section title="Reward source breakdown" subtitle="Refund restorations and legacy opening balances are excluded from issuance"><Table rows={data.sources} columns={[["Source",r=>r.label],["Issued",r=>fmt(r.issued)],["Users",r=>fmt(r.users)],["Transactions",r=>fmt(r.transactions)],["Average",r=>fmt(r.average,1)],["Share",r=>pct(r.share)],["₹ value",r=>money(r.estimatedValue)]]}/></Section>
 <div className="ra-grid ra-grid-3"><Section title="Daily streaks"><Stats items={[["Active streak users",fmt(data.streaks.users)],["Average streak",`${fmt(data.streaks.avg,1)} days`],["Longest current / ever",`${fmt(data.streaks.longestCurrent)} / ${fmt(data.streaks.longestEver)}`],["Claims / Damru",`${fmt(data.streaks.claims)} / ${fmt(data.streaks.issued)}`]]}/></Section><Section title="Referrals"><Stats items={[["Registered",fmt(data.referrals.registered)],["Qualified",fmt(data.referrals.qualified)],["Rewarded",fmt(data.referrals.rewarded)],["Conversion",pct(data.referrals.conversionRate)],["Referrer / referred",`${fmt(data.referrals.referrerDamru)} / ${fmt(data.referrals.referredDamru)}`]]}/></Section><Section title="Coupons & refunds"><Stats items={[["Reward coupons issued",fmt(data.coupons.issued)],["Coupon redemptions",fmt(data.coupons.redeemed)],["Expired unused",fmt(data.coupons.expiredUnused)],["Refund orders restored",fmt(data.kpis.refundOrders)],["Damru restored",fmt(data.kpis.restored)]]}/></Section></div>
 <Section title="Risk monitoring" subtitle="Admin-only review signals; kept separate from issuance metrics"><Stats items={[["Open risk events",fmt(data.risk.openEvents)],["High / critical",fmt(data.risk.highCriticalEvents)],["Damru associated",fmt(data.risk.damruAssociatedWithRisk)],["Reversed Damru associated",fmt(data.risk.reversedDamruAssociatedWithRisk)],["Reward debt at risk",fmt(data.risk.rewardDebtAtRisk)],["Referral / campaign alerts",`${fmt(data.risk.referralAlerts)} / ${fmt(data.risk.campaignAlerts)}`]]}/></Section>
 <div className="ra-grid ra-grid-2"><Section title="Achievements" subtitle={`${data.achievements.active} active · ${fmt(data.achievements.issued)} Damru`}><Table rows={data.achievements.rows} columns={[["Achievement",r=>r.name],["Unlocks",r=>fmt(r.unlocks)],["Reward",r=>fmt(r.reward)]]}/></Section><Section title="Missions" subtitle={`${data.missions.active} active · ${data.missions.participants} participants · ${fmt(data.missions.issued)} Damru`}><Table rows={data.missions.rows} columns={[["Mission",r=>r.name],["Participants",r=>fmt(r.participants)],["Completions",r=>fmt(r.completions)],["Reward",r=>fmt(r.reward)]]}/></Section></div>
 <Section title="Loyalty distribution" subtitle={`${fmt(data.loyalty.upgrades)} tier reward events · ${fmt(data.loyalty.issued)} Damru`}><Table rows={data.loyalty.rows} columns={[["Tier",r=>r.name],["Users",r=>fmt(r.users)],["Avg spend",r=>money(r.avgSpend)],["Avg balance",r=>fmt(r.avgBalance)]]}/></Section>
 <div className="ra-grid ra-grid-2"><Section title="Top balances" subtitle="Emails are masked"><Table rows={data.topUsers.rows} columns={[["Customer",r=><><b>{r.name}</b><small>{r.email}</small></>],["Balance",r=>fmt(r.balance)],["Earned",r=>fmt(r.lifetimeEarned)],["Redeemed",r=>fmt(r.lifetimeRedeemed)]]}/></Section><Section title="Highest earners in period"><Table rows={data.highEarners.rows} columns={[["Customer",r=><><b>{r.name}</b><small>{r.email}</small></>],["Earned",r=>fmt(r.earned)],["Balance",r=>fmt(r.balance)]]}/></Section></div>
 <Section title="Orders & reward value"><div className="ra-mini-grid"><Card label="Order rewards issued" value={fmt(data.orderRelationship.rewardIssued)}/><Card label="Order rewards reversed" value={fmt(data.orderRelationship.rewardReversed)} tone="#dc2626"/><Card label="Campaign reversed" value={fmt(data.orderRelationship.campaignReversed)} tone="#dc2626"/><Card label="Damru redeemed" value={fmt(data.orderRelationship.redeemedDamru)} tone="#2563eb"/><Card label="Estimated discount" value={money(data.orderRelationship.estimatedDiscount)} tone="#dc2626"/></div></Section><p className="ra-footnote">Generated {new Date(data.meta.generatedAt).toLocaleString("en-IN")} · Private 60-second cache · This dashboard never modifies rewards.</p>
 </>}</main>
}
