/* eslint-disable @typescript-eslint/no-explicit-any */
import mongoose from "mongoose";
import { RewardCampaignStatus } from "@/models/RewardCampaign";
const types=["ORDER_MULTIPLIER","ORDER_BONUS","CATEGORY_BONUS","REFERRAL_BOOST","MISSION_BOOST","NEW_USER_BONUS","LOYALTY_EXCLUSIVE","SEASONAL_BONUS"];
const modes=["FIXED_DAMRU","MULTIPLIER","PERCENT_BONUS"],audiences=["ALL_USERS","NEW_USERS","REPEAT_CUSTOMERS","LOYALTY_TIER","SELECTED_USERS"],triggers=["ORDER_DELIVERED","REFERRAL_REWARDED","MISSION_COMPLETED","REGISTRATION"],stacking=["NO_STACK","BEST_ONLY","STACK_ALLOWED"];
export function validateCampaignInput(body:Record<string,unknown>){if(!String(body.name||"").trim())return"Name is required.";if(!/^[A-Z0-9_-]{3,40}$/.test(String(body.code||"").trim().toUpperCase()))return"Code must be 3-40 letters, numbers, underscores, or hyphens.";if(!types.includes(String(body.campaignType)))return"Invalid campaign type.";if(!modes.includes(String(body.rewardMode)))return"Invalid reward mode.";if(!audiences.includes(String(body.audience)))return"Invalid audience.";if(!triggers.includes(String(body.trigger)))return"Invalid trigger.";if(!stacking.includes(String(body.stackingPolicy||"BEST_ONLY")))return"Invalid stacking policy.";if(!Number.isFinite(body.rewardValue)||Number(body.rewardValue)<=0)return"Reward value must be positive.";const start=new Date(String(body.startsAt)),end=new Date(String(body.endsAt));if(Number.isNaN(+start)||Number.isNaN(+end)||start>=end)return"A valid start before end is required.";for(const key of ["maxRewardPerEvent","maxRewardPerUser","globalBudgetDamru"]){const value=body[key];if(value!==null&&value!==undefined&&(!Number.isInteger(value)||Number(value)<=0))return`${key} must be a positive whole number.`}for(const key of ["eligibleBranches","eligibleCategories","eligibleMenuItems","eligibleLoyaltyTiers","selectedUsers","missionIds"]){if(body[key]!==undefined&&(!Array.isArray(body[key])||(body[key]as unknown[]).some(v=>!mongoose.isValidObjectId(String(v)))))return`Invalid ${key}.`}return null}
export function normalizeCampaignInput(body:Record<string,unknown>):Record<string,any>{const arrays=["eligibleBranches","eligibleCategories","eligibleMenuItems","eligibleLoyaltyTiers","selectedUsers","missionIds"];return{name:String(body.name).trim(),code:String(body.code).trim().toUpperCase(),description:String(body.description||"").trim(),campaignType:body.campaignType,rewardMode:body.rewardMode,rewardValue:Number(body.rewardValue),audience:body.audience,trigger:body.trigger,stackingPolicy:body.stackingPolicy||"BEST_ONLY",startsAt:new Date(String(body.startsAt)),endsAt:new Date(String(body.endsAt)),minimumOrderAmount:Number(body.minimumOrderAmount||0),newUserMaxAgeDays:Number(body.newUserMaxAgeDays||7),maxRewardPerEvent:body.maxRewardPerEvent?Number(body.maxRewardPerEvent):null,maxRewardPerUser:body.maxRewardPerUser?Number(body.maxRewardPerUser):null,globalBudgetDamru:body.globalBudgetDamru?Number(body.globalBudgetDamru):null,priority:Number(body.priority||0),isPublic:body.isPublic!==false,notificationCampaignId:body.notificationCampaignId||null,...Object.fromEntries(arrays.map(k=>[k,body[k]||[]]))}}
const transitions:Record<RewardCampaignStatus,RewardCampaignStatus[]>={DRAFT:["SCHEDULED","ACTIVE","CANCELLED"],SCHEDULED:["ACTIVE","PAUSED","CANCELLED"],ACTIVE:["PAUSED","ENDED","CANCELLED"],PAUSED:["ACTIVE","CANCELLED"],ENDED:[],CANCELLED:[]};
export const transitionAllowed=(from:RewardCampaignStatus,to:RewardCampaignStatus)=>transitions[from].includes(to);
