import mongoose, { Document, Model, Schema } from "mongoose";
export type RewardCampaignType="ORDER_MULTIPLIER"|"ORDER_BONUS"|"CATEGORY_BONUS"|"REFERRAL_BOOST"|"MISSION_BOOST"|"NEW_USER_BONUS"|"LOYALTY_EXCLUSIVE"|"SEASONAL_BONUS";
export type RewardCampaignStatus="DRAFT"|"SCHEDULED"|"ACTIVE"|"PAUSED"|"ENDED"|"CANCELLED";
export type RewardMode="FIXED_DAMRU"|"MULTIPLIER"|"PERCENT_BONUS";
export type CampaignAudience="ALL_USERS"|"NEW_USERS"|"REPEAT_CUSTOMERS"|"LOYALTY_TIER"|"SELECTED_USERS";
export type CampaignTrigger="ORDER_DELIVERED"|"REFERRAL_REWARDED"|"MISSION_COMPLETED"|"REGISTRATION";
export type StackingPolicy="NO_STACK"|"BEST_ONLY"|"STACK_ALLOWED";
export interface IRewardCampaign extends Document{name:string;code:string;description:string;campaignType:RewardCampaignType;status:RewardCampaignStatus;isPublic:boolean;startsAt:Date;endsAt:Date;audience:CampaignAudience;trigger:CampaignTrigger;rewardMode:RewardMode;rewardValue:number;minimumOrderAmount:number;newUserMaxAgeDays:number;maxRewardPerEvent:number|null;maxRewardPerUser:number|null;globalBudgetDamru:number|null;issuedDamru:number;rewardedUsers:number;qualifyingEvents:number;stackingPolicy:StackingPolicy;priority:number;eligibleBranches:mongoose.Types.ObjectId[];eligibleCategories:mongoose.Types.ObjectId[];eligibleMenuItems:mongoose.Types.ObjectId[];eligibleLoyaltyTiers:mongoose.Types.ObjectId[];selectedUsers:mongoose.Types.ObjectId[];missionIds:mongoose.Types.ObjectId[];notificationCampaignId?:mongoose.Types.ObjectId|null;createdBy?:mongoose.Types.ObjectId;updatedBy?:mongoose.Types.ObjectId;createdAt:Date;updatedAt:Date}
const schema=new Schema<IRewardCampaign>({name:{type:String,required:true,trim:true},code:{type:String,required:true,unique:true,uppercase:true,trim:true},description:{type:String,default:""},campaignType:{type:String,required:true,enum:["ORDER_MULTIPLIER","ORDER_BONUS","CATEGORY_BONUS","REFERRAL_BOOST","MISSION_BOOST","NEW_USER_BONUS","LOYALTY_EXCLUSIVE","SEASONAL_BONUS"]},status:{type:String,enum:["DRAFT","SCHEDULED","ACTIVE","PAUSED","ENDED","CANCELLED"],default:"DRAFT"},isPublic:{type:Boolean,default:true},startsAt:{type:Date,required:true},endsAt:{type:Date,required:true},audience:{type:String,enum:["ALL_USERS","NEW_USERS","REPEAT_CUSTOMERS","LOYALTY_TIER","SELECTED_USERS"],default:"ALL_USERS"},trigger:{type:String,enum:["ORDER_DELIVERED","REFERRAL_REWARDED","MISSION_COMPLETED","REGISTRATION"],required:true},rewardMode:{type:String,enum:["FIXED_DAMRU","MULTIPLIER","PERCENT_BONUS"],required:true},rewardValue:{type:Number,required:true,min:0},minimumOrderAmount:{type:Number,default:0,min:0},newUserMaxAgeDays:{type:Number,default:7,min:1},maxRewardPerEvent:{type:Number,default:null,min:0},maxRewardPerUser:{type:Number,default:null,min:0},globalBudgetDamru:{type:Number,default:null,min:0},issuedDamru:{type:Number,default:0,min:0},rewardedUsers:{type:Number,default:0,min:0},qualifyingEvents:{type:Number,default:0,min:0},stackingPolicy:{type:String,enum:["NO_STACK","BEST_ONLY","STACK_ALLOWED"],default:"BEST_ONLY"},priority:{type:Number,default:0},eligibleBranches:[{type:Schema.Types.ObjectId,ref:"Branch"}],eligibleCategories:[{type:Schema.Types.ObjectId,ref:"Category"}],eligibleMenuItems:[{type:Schema.Types.ObjectId,ref:"MenuItem"}],eligibleLoyaltyTiers:[{type:Schema.Types.ObjectId,ref:"LoyaltyTier"}],selectedUsers:[{type:Schema.Types.ObjectId,ref:"User"}],missionIds:[{type:Schema.Types.ObjectId,ref:"Mission"}],notificationCampaignId:{type:Schema.Types.ObjectId,ref:"NotificationCampaign",default:null},createdBy:{type:Schema.Types.ObjectId,ref:"Admin"},updatedBy:{type:Schema.Types.ObjectId,ref:"Admin"}},{timestamps:true});
schema.index({status:1,trigger:1,startsAt:1,endsAt:1}); schema.index({campaignType:1,status:1});
const RewardCampaign:Model<IRewardCampaign>=mongoose.models.RewardCampaign||mongoose.model<IRewardCampaign>("RewardCampaign",schema);export default RewardCampaign;
